name: BetterRaw
author: Ad5001
version: "0.2"
api: 1.13.0
main: Ad5001\BetterRaw\Main
website: http://ad5001.tk

description: Custom raw messages plugin for new api
commands:
 tellraw:
  description: "§6This is a tellraw command like in PC. Display in the chat of a specific player a custom raw message"
  usage: "§a/tellraw <player> <message...>"
  permission: braw.command.tellraw
  aliases: [tr]
 tellworldraw:
  description: "§6Display in the chat of every players in a specific world a custom raw message"
  usage: "§a/tellworldraw <world> <message...>"
  permission: braw.command.tellworldraw
  aliases: [twr]
 saygmraw:
  description: "§6Display in the chat of every players in a specific gamemode a custom raw message"
  usage: "§a/saygmraw <world> <message...>"
  permission: braw.command.saygmraw
  aliases: [sgmr]
 tip:
  description: "§6Display a tip to a specific player"
  usage: "§a/tip <world> <message...>"
  permission: braw.command.tip
 popup:
  description: "§6Display a popup to a specific player"
  usage: "§a/popup <world> <message...>"
  permission: braw.command.popup
  aliases: [pop]
 popupworld:
  description: "§6Display a popup to everyone in a specific world"
  usage: "§a/popupworld <world> <message...>"
  permission: braw.command.popupworld
  aliases: [pw]
 tipworld:
  description: "§6Display a tip to everyone in a specific world"
  usage: "§a/tipworld <world> <message...>"
  permission: braw.command.tipworld
  aliases: [tw]
permissions:
   braw.command.tellraw:
    default: op
    description: "§6Send the player a raw message you want"
   braw.command.tellworldraw:
    default: op
    description: "§6Display in the chat of every players in a specific world a custom raw message"
   braw.command.saygmraw:
    default: op
    description: "§6Display in the chat of every players in a specific gamemode a custom raw message"
   braw.command.tip:
    default: op
    description: "§6Display a popup to a specific player"
   braw.command.popup:
    default: op
    description: "§6Display a popup to a specific player"
   braw.command.popupworld:
    default: op
    description: "§6Display a popup to everyone in a specific world"
   braw.command.tipworld:
    default: op
    description: "§6Display a tip to everyone in a specific world"
...
